#!/usr/bin/env bash

_OS=$(`dirname $0`/get-os)

## COPY
# [[ $_OS = 'mac' ]] && echo 'copy: reattach-to-user-namespace pbcopy'
[[ $_OS = 'mac'   ]] && echo 'copy: pbcopy'
[[ $_OS = 'linux' ]] && echo 'copy: xsel -ip && xsel -op | xsel -ib'
[[ $_OS = 'wsl'   ]] && echo 'copy: win32yank.exe -i'

## PASTE
[[ $_OS = 'mac'   ]] && echo 'paste: pbpaste'
[[ $_OS = 'linux' ]] && echo 'paste: xsel -ob'
[[ $_OS = 'wsl'   ]] && echo 'paste: win32yank.exe -o'

