#!/usr/bin/env bash

function show-window-status {
  if pgrep -flaP $_TMUX_PANE_PID ssh; then
    IS_SSH=true
  fi

  if [[ "$_TMUX_IS_CURRENT_PANE" = true ]]; then
    if [ -n "$IS_SSH" ]; then
      echo -n '#[fg=colour255,bg=#00aa22,bold]'
    else
      echo -n '#[fg=colour255,bg=#cc4400,bold]'
    fi
  fi

  echo -n " #I: "

  # zsh
  if [[ "$_TMUX_WINDOW_NAME" = 'zsh' || "$_TMUX_WINDOW_NAME" = 'reattach-to-user-namespace' ]]; then
    if [[ $_TMUX_PANE_CURRENT_PATH = "$HOME" ]]; then
      echo -n 'HOME';
    else
      basename $_TMUX_PANE_CURRENT_PATH | perl -pe "chomp; s|^$HOME|~|"

      repo_name="$(cd $_TMUX_PANE_CURRENT_PATH && basename "$(git rev-parse --show-toplevel 2> /dev/null)")"
      [ -n "$repo_name" ] && echo -n " ($repo_name)"
    fi
  # ssh
  elif [ -n "$IS_SSH" ]; then
    ssh_command_line="$(pgrep -flaP $_TMUX_PANE_PID ssh | grep -Po '(?<=/usr/bin/)?ssh\s.*$' | tail -n1)"
    #ps -o command -p $_TMUX_PANE_PID | grep -Po '(?<=/usr/bin/)?ssh\s.*$'
    echo -n "$ssh_command_line"
  else
    echo -n '#W';
  fi

  echo -n ' '
}

# output all at once
echo -n "$(show-window-status)"
