#!/usr/bin/env bash

if [ "$(uname)" == 'Darwin' ]; then
  echo mac
elif [[ -n "$(uname -r | grep -i 'microsoft')" ]]; then
  echo wsl
elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]; then
  echo cygwin
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  echo linux
else
  echo ''
fi
